version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      testing:
        patterns:
          - "Moq.*"
          - "xunit.*"
          - "coverlet.*"
          - "Microsoft.NET.Test.Sdk"
      Microsoft:
        patterns:
          - "Microsoft.*"
          - "System.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
